name: Build and Deploy
on:
  push:
    tags:
      - "*.*.*"

jobs:
  prepare:
    strategy:
      matrix:
        arch: ["linux/arm/v7", "linux/arm64", "linux/amd64"]
    runs-on: ubuntu-latest
    outputs:
      arch: ${{ steps.arch.outputs.value }}
      list_archs: ${{ steps.list-arch.outputs.matrix }}
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ matrix.arch }}

      - name: Get tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
        id: tag

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push (arm64)
        uses: docker/build-push-action@v3
        with:
          file: ./build/docker/Dockerfile
          push: true
          tags: rocklviv/cloudflare-dns-updater:${{ steps.tag.outputs.tag }}-arm64
          platforms: "linux/arm64"

      - name: Build and Push (armv7)
        uses: docker/build-push-action@v3
        with:
          file: ./build/docker/Dockerfile
          push: true
          tags: rocklviv/cloudflare-dns-updater:${{ steps.tag.outputs.tag }}-armv7
          platforms: "linux/arm/v7"
      
      - name: Build and Push (amd64)
        uses: docker/build-push-action@v3
        with:
          file: ./build/docker/Dockerfile
          push: true
          tags: rocklviv/cloudflare-dns-updater:${{ steps.tag.outputs.tag }}-amd64
          platforms: "linux/amd64"
