name: Build and Deploy
on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    strategy:
      matrix:
        arch: ["linux/arm/v7", "linux/arm64", "linux/amd64"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ matrix.arch }}

      - name: Get tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
        id: tag

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - uses: mad9000/actions-find-and-replace-string@2
        with:
          source: ${{ matrix.arch }}
          find: ["linux/", "/7"]
          replace: ""
        id: arch

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          file: ./build/docker/Dockerfile
          push: true
          tags: rocklviv/cloudflare-dns-updater:${{ steps.tag.outputs.tag }}-${{ steps.arch.outputs.value }}
          platforms: ${{ matrix.arch }}
