name: Build and Deploy
on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    strategy:
      matrix:
        arch: ["armv7", "arm64", "amd64"]
        build_platforms: [{"os": "linux/arm/v7", "arch": "arm32v7"}, {"os":"linux/arm64", "arch": "arm64v8"}, {"os":"linux/amd64", "arch":"amd64"}]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
        id: tag

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          file: ./build/docker/Dockerfile
          push: true
          tags: rocklviv/cloudflare-dns-updater:${{ steps.tag.outputs.tag }}-${{ matrix.build_platforms }}
          platforms: linux/${{ matrix.build_platforms.os }}
          build-args:
            BUILD_ARCH: ${{ matrix.build_platforms.arch }}