name: Go code verify
on:
    pull_request:
        types: [opened, reopened, edited, synchronize]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                  go-version: 1.18
            - name: Check if go fmt is required
              id: gofmt
              uses: Jerome1337/gofmt-action@v1.0.5
              with:
                  gofmt-path: "./"
                  gofmt-flags: ""
            - name: Add comment to PR
              if: failure() && steps.gofmt.outcome == 'failure'
              uses: mshick/add-pr-comment@v2
              with:
                  message: |
                    **Failed PR Check**
                    "```${{ steps.gofmt.gofmt-output }}```"
