name: Go code verify
on:
    pull_request:
        types: [opened, reopened, edited, synchronize]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Run govet
              run: go vet ./
